version: '3.8'
services:
  master:
    build: ./master
    ports:
      - "8000:8000"
    environment:
      - SECONDARIES=http://s1:8001,http://s2:8002
      - MASTER_HOST=master
  s1:
    build: ./secondary
    ports:
      - "8001:8001"
    environment:
      - REPLICA_ID=s1
      - REPLICA_PORT=8001
      - MASTER_URL=http://master:8000
      - PROCESS_DELAY_MS=3000
  s2:
    build: ./secondary
    ports:
      - "8002:8002"
    environment:
      - REPLICA_ID=s2
      - REPLICA_PORT=8002
      - MASTER_URL=http://master:8000
      - PROCESS_DELAY_MS=10000
      - START_DELAY_SEC=0
