version: "3.9"

services:
  master:
    build: ./master
    ports:
      - "5000:5000"
    environment:
      - SECONDARIES=http://secondary1:5001,http://secondary2:5001
    depends_on:
      - secondary1
      - secondary2

  secondary1:
    build: ./secondary
    ports:
      - "5001:5001"

  secondary2:
    build: ./secondary
    ports:
      - "5002:5001"